export const variations = [
  { label: "Red", value: "red" },
  { label: "Blue", value: "blue" },
];

export const brands = [
  {
    brand: "Apple",
    models: [
      { id: "iPhone (1st generation)", name: "iPhone (1st generation)" },
      { id: "iPhone 3G", name: "iPhone 3G" },
      { id: "iPhone 3GS", name: "iPhone 3GS" },
      { id: "iPhone 4", name: "iPhone 4" },
      { id: "iPhone 4S", name: "iPhone 4S" },
      { id: "iPhone 5", name: "iPhone 5" },
      { id: "iPhone 5C", name: "iPhone 5C" },
      { id: "iPhone 5S", name: "iPhone 5S" },
      { id: "iPhone 6", name: "iPhone 6" },
      { id: "iPhone 6 Plus", name: "iPhone 6 Plus" },
      { id: "iPhone 6S", name: "iPhone 6S" },
      { id: "iPhone 6S Plus", name: "iPhone 6S Plus" },
      { id: "iPhone SE (1st generation)", name: "iPhone SE (1st generation)" },
      { id: "iPhone 7", name: "iPhone 7" },
      { id: "iPhone 7 Plus", name: "iPhone 7 Plus" },
      { id: "iPhone 8", name: "iPhone 8" },
      { id: "iPhone 8 Plus", name: "iPhone 8 Plus" },
      { id: "iPhone X", name: "iPhone X" },
      { id: "iPhone XR", name: "iPhone XR" },
      { id: "iPhone XS", name: "iPhone XS" },
      { id: "iPhone XS Max", name: "iPhone XS Max" },
      { id: "iPhone 11", name: "iPhone 11" },
      { id: "iPhone 11 Pro", name: "iPhone 11 Pro" },
      { id: "iPhone 11 Pro Max", name: "iPhone 11 Pro Max" },
      { id: "iPhone SE (2nd generation)", name: "iPhone SE (2nd generation)" },
      { id: "iPhone 12 Mini", name: "iPhone 12 Mini" },
      { id: "iPhone 12", name: "iPhone 12" },
      { id: "iPhone 12 Pro", name: "iPhone 12 Pro" },
      { id: "iPhone 12 Pro Max", name: "iPhone 12 Pro Max" },
      { id: "iPhone 13 Mini", name: "iPhone 13 Mini" },
      { id: "iPhone 13", name: "iPhone 13" },
      { id: "iPhone 13 Pro", name: "iPhone 13 Pro" },
      { id: "iPhone 13 Pro Max", name: "iPhone 13 Pro Max" },
      { id: "iPhone SE (3rd generation)", name: "iPhone SE (3rd generation)" },
      { id: "iPhone 14", name: "iPhone 14" },
      { id: "iPhone 14 Plus", name: "iPhone 14 Plus" },
      { id: "iPhone 14 Pro", name: "iPhone 14 Pro" },
      { id: "iPhone 14 Pro Max", name: "iPhone 14 Pro Max" },
    ],
  },
  {
    brand: "Samsung",
    models: [
      { id: "Galaxy S", name: "Galaxy S" },
      { id: "Galaxy S II", name: "Galaxy S II" },
      { id: "Galaxy S III", name: "Galaxy S III" },
      { id: "Galaxy S4", name: "Galaxy S4" },
      { id: "Galaxy S5", name: "Galaxy S5" },
      { id: "Galaxy S6", name: "Galaxy S6" },
      { id: "Galaxy S6 Edge", name: "Galaxy S6 Edge" },
      { id: "Galaxy S7", name: "Galaxy S7" },
      { id: "Galaxy S7 Edge", name: "Galaxy S7 Edge" },
      { id: "Galaxy S8", name: "Galaxy S8" },
      { id: "Galaxy S8+", name: "Galaxy S8+" },
      { id: "Galaxy S9", name: "Galaxy S9" },
      { id: "Galaxy S9+", name: "Galaxy S9+" },
      { id: "Galaxy S10e", name: "Galaxy S10e" },
      { id: "Galaxy S10", name: "Galaxy S10" },
      { id: "Galaxy S10+", name: "Galaxy S10+" },
      { id: "Galaxy S20", name: "Galaxy S20" },
      { id: "Galaxy S20+", name: "Galaxy S20+" },
      { id: "Galaxy S20 Ultra", name: "Galaxy S20 Ultra" },
      { id: "Galaxy S21", name: "Galaxy S21" },
      { id: "Galaxy S21+", name: "Galaxy S21+" },
      { id: "Galaxy S21 Ultra", name: "Galaxy S21 Ultra" },
      { id: "Galaxy S22", name: "Galaxy S22" },
      { id: "Galaxy S22+", name: "Galaxy S22+" },
      { id: "Galaxy S22 Ultra", name: "Galaxy S22 Ultra" },
      { id: "Galaxy S23", name: "Galaxy S23" },
      { id: "Galaxy S23+", name: "Galaxy S23+" },
      { id: "Galaxy S23 Ultra", name: "Galaxy S23 Ultra" },
      { id: "Galaxy Z Fold", name: "Galaxy Z Fold" },
      { id: "Galaxy Z Fold 2", name: "Galaxy Z Fold 2" },
      { id: "Galaxy Z Fold 3", name: "Galaxy Z Fold 3" },
      { id: "Galaxy Z Fold 4", name: "Galaxy Z Fold 4" },
      { id: "Galaxy Z Flip", name: "Galaxy Z Flip" },
      { id: "Galaxy Z Flip 5", name: "Galaxy Z Flip 5" },
      { id: "Galaxy A5", name: "Galaxy A5" },
      { id: "Galaxy A7", name: "Galaxy A7" },
      { id: "Galaxy A9", name: "Galaxy A9" },
      { id: "Galaxy A10e", name: "Galaxy A10e" },
      { id: "Galaxy A30", name: "Galaxy A30" },
      { id: "Galaxy A40", name: "Galaxy A40" },
      { id: "Galaxy A50", name: "Galaxy A50" },
      { id: "Galaxy A51", name: "Galaxy A51" },
      { id: "Galaxy A52", name: "Galaxy A52" },
      { id: "Galaxy A53 5G", name: "Galaxy A53 5G" },
      { id: "Galaxy A54 5G", name: "Galaxy A54 5G" },
      { id: "Galaxy M10", name: "Galaxy M10" },
      { id: "Galaxy M20", name: "Galaxy M20" },
      { id: "Galaxy M30", name: "Galaxy M30" },
      { id: "Galaxy M40", name: "Galaxy M40" },
      { id: "Galaxy M50", name: "Galaxy M50" },
    ],
  },
  {
    brand: "Google",
    models: [
      { id: "Pixel", name: "Pixel" },
      { id: "Pixel XL", name: "Pixel XL" },
      { id: "Pixel 2", name: "Pixel 2" },
      { id: "Pixel 2 XL", name: "Pixel 2 XL" },
      { id: "Pixel 3", name: "Pixel 3" },
      { id: "Pixel 3 XL", name: "Pixel 3 XL" },
      { id: "Pixel 3a", name: "Pixel 3a" },
      { id: "Pixel 3a XL", name: "Pixel 3a XL" },
      { id: "Pixel 4", name: "Pixel 4" },
      { id: "Pixel 4 XL", name: "Pixel 4 XL" },
      { id: "Pixel 4a", name: "Pixel 4a" },
      { id: "Pixel 4a 5G", name: "Pixel 4a 5G" },
      { id: "Pixel 5", name: "Pixel 5" },
      { id: "Pixel 5a 5G", name: "Pixel 5a 5G" },
      { id: "Pixel 6", name: "Pixel 6" },
      { id: "Pixel 6 Pro", name: "Pixel 6 Pro" },
      { id: "Pixel 6a", name: "Pixel 6a" },
      { id: "Pixel 7", name: "Pixel 7" },
      { id: "Pixel 7 Pro", name: "Pixel 7 Pro" },
      { id: "Pixel 8", name: "Pixel 8" },
      { id: "Pixel 8 Pro", name: "Pixel 8 Pro" },
    ],
  },
  {
    brand: "OnePlus",
    models: [
      { id: "OnePlus One", name: "OnePlus One" },
      { id: "OnePlus 2", name: "OnePlus 2" },
      { id: "OnePlus 3", name: "OnePlus 3" },
      { id: "OnePlus 3T", name: "OnePlus 3T" },
      { id: "OnePlus 5", name: "OnePlus 5" },
      { id: "OnePlus 5T", name: "OnePlus 5T" },
      { id: "OnePlus 6", name: "OnePlus 6" },
      { id: "OnePlus 6T", name: "OnePlus 6T" },
      { id: "OnePlus 7", name: "OnePlus 7" },
      { id: "OnePlus 7 Pro", name: "OnePlus 7 Pro" },
      { id: "OnePlus 7T", name: "OnePlus 7T" },
      { id: "OnePlus 7T Pro", name: "OnePlus 7T Pro" },
      { id: "OnePlus 8", name: "OnePlus 8" },
      { id: "OnePlus 8 Pro", name: "OnePlus 8 Pro" },
      { id: "OnePlus 8T", name: "OnePlus 8T" },
      { id: "OnePlus 9", name: "OnePlus 9" },
      { id: "OnePlus 9 Pro", name: "OnePlus 9 Pro" },
      { id: "OnePlus 9R", name: "OnePlus 9R" },
      { id: "OnePlus 10 Pro", name: "OnePlus 10 Pro" },
      { id: "OnePlus 10T", name: "OnePlus 10T" },
      { id: "OnePlus 11", name: "OnePlus 11" },
    ],
  },
  {
    brand: "Motorola",
    models: [
      { id: "Moto X", name: "Moto X" },
      { id: "Moto X+1", name: "Moto X+1" },
      { id: "Moto X Play", name: "Moto X Play" },
      { id: "Moto G", name: "Moto G" },
      { id: "Moto G2", name: "Moto G2" },
      { id: "Moto G3", name: "Moto G3" },
      { id: "Moto G4", name: "Moto G4" },
      { id: "Moto G5", name: "Moto G5" },
      { id: "Moto G6", name: "Moto G6" },
      { id: "Moto G7", name: "Moto G7" },
      { id: "Moto G8", name: "Moto G8" },
      { id: "Moto G9", name: "Moto G9" },
      { id: "Moto Z", name: "Moto Z" },
      { id: "Moto Z Play", name: "Moto Z Play" },
      { id: "Moto Z2 Force", name: "Moto Z2 Force" },
      { id: "Moto Z3", name: "Moto Z3" },
      { id: "Moto Z4", name: "Moto Z4" },
      { id: "Moto Edge", name: "Moto Edge" },
      { id: "Moto Edge+", name: "Moto Edge+" },
      { id: "Moto Edge 20", name: "Moto Edge 20" },
      { id: "Moto Edge 30", name: "Moto Edge 30" },
      { id: "Moto G Stylus 5G", name: "Moto G Stylus 5G" },
    ],
  },
];

export const brandNames = [
  { id: "Apple", name: "Apple" },
  { id: "Samsung", name: "Samsung" },
  { id: "Huawei", name: "Huawei" },
  { id: "Xiaomi", name: "Xiaomi" },
  { id: "OnePlus", name: "OnePlus" },
  { id: "Oppo", name: "Oppo" },
  { id: "Motorola", name: "Motorola" },
  { id: "Google", name: "Google" },
  { id: "Sony", name: "Sony" },
  { id: "LG", name: "LG" },
  { id: "Realme", name: "Realme" },
  { id: "Asus", name: "Asus" },
  { id: "Vivo", name: "Vivo" },
];
